server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

spring:

  profiles:
    active: sharding-tbl-ms,dev,common
  main:
    allow-bean-definition-overriding: true
  application:
    name: myu-console
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root



